/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IEnumVARIANT */

#ifndef _Included_jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IEnumVARIANT
#define _Included_jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IEnumVARIANT
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: IID */
/* Inaccessible static: class_00024jp_00024ne_00024so_net_00024ga2_00024no_ji_00024jcom_00024ReleaseManager */
/* Inaccessible static: IID */
/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IEnumVARIANT
 * Method:    _next
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_IEnumVARIANT__1next__
  (JNIEnv *, jobject);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IEnumVARIANT
 * Method:    _next
 * Signature: (I)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_IEnumVARIANT__1next__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IEnumVARIANT
 * Method:    _reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_IEnumVARIANT__1reset
  (JNIEnv *, jobject);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IEnumVARIANT
 * Method:    _skip
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_IEnumVARIANT__1skip
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
