/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IUnknown */

#ifndef _Included_jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IUnknown
#define _Included_jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IUnknown
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: IID */
/* Inaccessible static: class_00024jp_00024ne_00024so_net_00024ga2_00024no_ji_00024jcom_00024ReleaseManager */
/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IUnknown
 * Method:    _addRef
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_IUnknown__1addRef
  (JNIEnv *, jobject);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IUnknown
 * Method:    _release
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_IUnknown__1release
  (JNIEnv *, jobject);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IUnknown
 * Method:    _queryInterface
 * Signature: (Ljp/ne/so_net/ga2/no_ji/jcom/GUID;)I
 */
JNIEXPORT jint JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_IUnknown__1queryInterface
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
