/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeLib */

#ifndef _Included_jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeLib
#define _Included_jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeLib
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: IID */
/* Inaccessible static: IID */
/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeLib
 * Method:    _getDocumentation
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_ITypeLib__1getDocumentation
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeLib
 * Method:    _getTypeInfo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_ITypeLib__1getTypeInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeLib
 * Method:    _getTypeInfoCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_ITypeLib__1getTypeInfoCount
  (JNIEnv *, jobject);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeLib
 * Method:    _getTLibAttr
 * Signature: ()Ljp/ne/so_net/ga2/no_ji/jcom/ITypeLib$TLibAttr;
 */
JNIEXPORT jobject JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_ITypeLib__1getTLibAttr
  (JNIEnv *, jobject);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeLib
 * Method:    _loadTypeLibEx
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_ITypeLib__1loadTypeLibEx
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeLib
 * Method:    _loadRegTypeLib
 * Signature: (Ljp/ne/so_net/ga2/no_ji/jcom/GUID;II)I
 */
JNIEXPORT jint JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_ITypeLib__1loadRegTypeLib
  (JNIEnv *, jclass, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
