/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ne_so_0005fnet_ga2_no_0005fji_jcom_Com */

#ifndef _Included_jp_ne_so_0005fnet_ga2_no_0005fji_jcom_Com
#define _Included_jp_ne_so_0005fnet_ga2_no_0005fji_jcom_Com
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_Com
 * Method:    _CLSIDFromProgID
 * Signature: (Ljava/lang/String;)Ljp/ne/so_net/ga2/no_ji/jcom/GUID;
 */
JNIEXPORT jobject JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_Com__1CLSIDFromProgID
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_Com
 * Method:    _ProgIDFromCLSID
 * Signature: (Ljp/ne/so_net/ga2/no_ji/jcom/GUID;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_Com__1ProgIDFromCLSID
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
