/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeInfo */

#ifndef _Included_jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeInfo
#define _Included_jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeInfo
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: IID */
/* Inaccessible static: class_00024jp_00024ne_00024so_net_00024ga2_00024no_ji_00024jcom_00024ReleaseManager */
/* Inaccessible static: IID */
#undef jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeInfo_MEMBERID_NIL
#define jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeInfo_MEMBERID_NIL -1L
/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeInfo
 * Method:    _getDocumentation
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_ITypeInfo__1getDocumentation
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeInfo
 * Method:    _getNames
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_ITypeInfo__1getNames
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeInfo
 * Method:    _getTypeAttr
 * Signature: ()Ljp/ne/so_net/ga2/no_ji/jcom/ITypeInfo$TypeAttr;
 */
JNIEXPORT jobject JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_ITypeInfo__1getTypeAttr
  (JNIEnv *, jobject);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeInfo
 * Method:    _getFuncDesc
 * Signature: (I)Ljp/ne/so_net/ga2/no_ji/jcom/ITypeInfo$FuncDesc;
 */
JNIEXPORT jobject JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_ITypeInfo__1getFuncDesc
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeInfo
 * Method:    _getVarDesc
 * Signature: (I)Ljp/ne/so_net/ga2/no_ji/jcom/ITypeInfo$VarDesc;
 */
JNIEXPORT jobject JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_ITypeInfo__1getVarDesc
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeInfo
 * Method:    _getImplType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_ITypeInfo__1getImplType
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeInfo
 * Method:    _getTypeLib
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_ITypeInfo__1getTypeLib
  (JNIEnv *, jobject);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_ITypeInfo
 * Method:    _getRefTypeInfo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_ITypeInfo__1getRefTypeInfo
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
