/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch */

#ifndef _Included_jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch
#define _Included_jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: IID */
/* Inaccessible static: class_00024jp_00024ne_00024so_net_00024ga2_00024no_ji_00024jcom_00024ReleaseManager */
/* Inaccessible static: IID */
#undef jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch_METHOD
#define jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch_METHOD 1L
#undef jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch_PROPERTYGET
#define jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch_PROPERTYGET 2L
#undef jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch_PROPERTYPUT
#define jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch_PROPERTYPUT 4L
#undef jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch_PROPERTYPUTREF
#define jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch_PROPERTYPUTREF 8L
/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch
 * Method:    _create
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_IDispatch__1create
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch
 * Method:    _get
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_IDispatch__1get__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch
 * Method:    _get
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_IDispatch__1get__Ljava_lang_String_2_3Ljava_lang_Object_2
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch
 * Method:    _put
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_IDispatch__1put
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch
 * Method:    _method
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_IDispatch__1method
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch
 * Method:    _getTypeInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_IDispatch__1getTypeInfo
  (JNIEnv *, jobject);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch
 * Method:    _invoke
 * Signature: (II[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_IDispatch__1invoke
  (JNIEnv *, jobject, jint, jint, jobjectArray);

/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IDispatch
 * Method:    _getIDsOfNames
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_IDispatch__1getIDsOfNames
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
