/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IPersist */

#ifndef _Included_jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IPersist
#define _Included_jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IPersist
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: IID */
/* Inaccessible static: IID */
/*
 * Class:     jp_ne_so_0005fnet_ga2_no_0005fji_jcom_IPersist
 * Method:    _getClassID
 * Signature: ()Ljp/ne/so_net/ga2/no_ji/jcom/GUID;
 */
JNIEXPORT jobject JNICALL Java_jp_ne_so_1net_ga2_no_1ji_jcom_IPersist__1getClassID
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
