var ntUsedBy = new Object();
ntUsedBy["JavaArrayAllocator"]=["JavaAllocator","JavaArrayAllocator"];
ntUsedBy["CreateBatchStatement"]=["JdbcStatements"];
ntUsedBy["FileSystemStatements"]=["Statement"];
ntUsedBy["RelationalExpr"]=["EqualityExpr"];
ntUsedBy["DeleteStatement"]=["Statement"];
ntUsedBy["XsltStatement"]=["Statement"];
ntUsedBy["Assignment"]=["Expr"];
ntUsedBy["JavaAllocator"]=["PrimaryExpr"];
ntUsedBy["IfStatement"]=["Statement"];
ntUsedBy["SgmlHandlerDeclaration"]=["Script"];
ntUsedBy["Directives"]=["Script"];
ntUsedBy["LambdaDeclaration"]=["PrimaryExpr"];
ntUsedBy["ReturnStatement"]=["Statement"];
ntUsedBy["DynamicStatements"]=["Statement"];
ntUsedBy["LinesStatement"]=["Statement"];
ntUsedBy["FSFileModStatements"]=["FileSystemStatements"];
ntUsedBy["ForInStatement"]=["ForStatements"];
ntUsedBy["PrepareStatement"]=["JdbcStatements"];
ntUsedBy["Dom"]=["ArrayAllocator","StructAllocator","JavaArrayAllocator","Assignment","LocalVariableDeclaration","ReturnStatement"];
ntUsedBy["ConnectStatement"]=["JdbcStatements"];
ntUsedBy["Arguments"]=["JavaAllocator","AtomicExpr","ThrowStatement","StartThreadStatement","BindVariableList"];
ntUsedBy["JavaPrimitiveTypes"]=["JavaType","JavaAllocator","Arguments"];
ntUsedBy["PrefixExpr"]=["UnaryExpr"];
ntUsedBy["ThreadDeclaration"]=["Script"];
ntUsedBy["Expr"]=["UsageDeclaration","IncludeDirective","ConstantDefinition","FormalParameters","ConditionalExpr","MemberInitList","AnonMemberInitList","ArrayAllocator","StructAllocator","SetAllocator","ComparatorDecl","JavaArrayAllocator","AtomicExpr","Arguments","Mixture","Assignment","LocalVariableDeclaration","Statement","IfStatement","SwitchStatement","WhileStatement","DoWhileStatement","ForStatement","ForInStatement","ForFromToStatement","RepeatStatement","LinesStatement","ReturnStatement","ThrowStatement","StartThreadStatement","DynamicStatements","PrintStatement","PrintArgument","PrintTableDataStatement","EchoStatement","DeleteStatement","VoidStatement","SgmlStatement","ScheduleStatement","ExecStatement","SCPStatement","MailStatement","FSListStatement","FSFileModStatements","FSMakeRemoveDirStatements","FSCopyStatement","FSMoveStatement","ConnectStatement","BindVariableList","DumpTableStatement","Dom","XmlStatement","XsltStatement"];
ntUsedBy["PreparedExecuteQueryStatement"]=["JdbcStatements"];
ntUsedBy["FSMoveStatement"]=["FileSystemStatements"];
ntUsedBy["FSMakeRemoveDirStatements"]=["FileSystemStatements"];
ntUsedBy["DoWHileStatement"]=["Statement"];
ntUsedBy["ExecuteUpdateStatement"]=["JdbcStatements"];
ntUsedBy["PrintTableDataStatement"]=["Statement"];
ntUsedBy["EchoStatement"]=["Statement"];
ntUsedBy["JavaClassName"]=["JavaClassShortcuts","JavaExtensionDefinition","JavaType","StaticJavaFunctionDeclaration","JavaAllocator","JavaClassAllocator","AtomicExpr","ThrowStatement"];
ntUsedBy["MemberInitList"]=["ObjectAllocator","ConnectStatement","XsltStatement"];
ntUsedBy["WhileStatement"]=["Statement"];
ntUsedBy["ClassDefinition"]=["Script"];
ntUsedBy["SetAllocator"]=["ConstantDefinition","Assignment","LocalVariableDeclaration","ReturnStatement"];
ntUsedBy["PostfixExpr"]=["UnaryExprNotPlusMinus"];
ntUsedBy["PreparedExecuteStatement"]=["JdbcStatements"];
ntUsedBy["StaticJavaFunctionDeclaration"]=["Script"];
ntUsedBy["EqualityExpr"]=["AndExpr"];
ntUsedBy["PrintStatement"]=["Statement"];
ntUsedBy["SgmlEvent"]=["SgmlStatement","SgmlHandlerDeclaration"];
ntUsedBy["PrimaryExpr"]=["PrefixExpr","PostfixExpr","Assignment","PrintStatement","PrintTableDataStatement","GuiEventsStatement","BindVariableList"];
ntUsedBy["StartThreadStatement"]=["Statement"];
ntUsedBy["ObjectAllocator"]=["PrimaryExpr"];
ntUsedBy["ForStatement"]=["ForStatements"];
ntUsedBy["ContinueStatement"]=["Statement"];
ntUsedBy["ScheduleStatement"]=["Statement"];
ntUsedBy["Statement"]=["Script","Block","SimpleBlock","IfStatement","SwitchStatement","WhileStatement","ForStatement","ForInStatement","ForFromToStatement","SgmlStatement","SgmlHandlerDeclaration","GuiEventsStatement","XmlStatement"];
ntUsedBy["PragmaType"]=["Pragma"];
ntUsedBy["UsageDeclaration"]=["Script"];
ntUsedBy["BreakStatement"]=["Statement"];
ntUsedBy["FSListStatement"]=["FileSystemStatements"];
ntUsedBy["XmlInitList"]=["Dom","XmlStatement"];
ntUsedBy["ArrayAllocator"]=["ConstantDefinition","ArrayAllocator","Assignment","LocalVariableDeclaration","ReturnStatement"];
ntUsedBy["AndExpr"]=["ExclusiveOrExpr"];
ntUsedBy["ForFromToStatement"]=["ForStatements"];
ntUsedBy["InclusiveOrExpr"]=["ConditionalAndExpr"];
ntUsedBy["HereDoc"]=["ConstantDefinition","ArrayAllocator","StructAllocator","JavaArrayAllocator","Assignment","LocalVariableDeclaration","ReturnStatement","DynamicStatements","PrintArgument","MailStatement","ExecuteAnyStatement"];
ntUsedBy["ImportStatement"]=["Script"];
ntUsedBy["FSCopyStatement"]=["FileSystemStatements"];
ntUsedBy["Mixture"]=["HereDoc","PrepareStatement","PreparedExecuteStatement","PreparedExecuteQueryStatement","PreparedExecuteUpdateStatement","ExecuteQueryStatement","ExecuteSqlStatement","RawSqlList","AddBatchStatement","DumpTableStatement"];
ntUsedBy["ComparatorDecl"]=["ClassDefinition","ObjectAllocator","SetAllocator"];
ntUsedBy["SwitchStatement"]=["Statement"];
ntUsedBy["BindVariableList"]=["PreparedExecuteStatement","PreparedExecuteQueryStatement","PreparedExecuteUpdateStatement","ExecuteQueryStatement","ExecuteUpdateStatement","ExecuteSqlStatement"];
ntUsedBy["Literal"]=["Pragma","UnaryExprNotPlusMinus"];
ntUsedBy["JavaClassAllocator"]=["PrimaryExpr"];
ntUsedBy["UnaryExprNotPlusMinus"]=["UnaryExpr"];
ntUsedBy["GuiEventsStatement"]=["Statement"];
ntUsedBy["AddBatchStatement"]=["JdbcStatements"];
ntUsedBy["JavaExtensionDefinition"]=["Script"];
ntUsedBy["Pragma"]=["Directives"];
ntUsedBy["ExecuteAnyStatement"]=["JdbcStatements"];
ntUsedBy["ArgumentList"]=["Statement","DynamicStatements"];
ntUsedBy["UnaryExpr"]=["MultiplicativeExpr","UnaryExpr","UnaryExprNotPlusMinus"];
ntUsedBy["XmlStatement"]=["Statement"];
ntUsedBy["PreapredExecuteUpdateStatement"]=["JdbcStatements"];
ntUsedBy["JavaType"]=["JavaExtensionDefinition"];
ntUsedBy["AdditiveExpr"]=["ShiftExpr"];
ntUsedBy["ExclusiveOrExpr"]=["InclusiveOrExpr"];
ntUsedBy["Block"]=["JavaExtensionDefinition","ConstructorDeclaration","FunctionDeclaration","LambdaDeclaration","ThreadDeclaration","Statement","StartThreadStatement","FSCopyStatement"];
ntUsedBy["RepeatStatement"]=["ForStatements"];
ntUsedBy["ConstantDefinition"]=["Script"];
ntUsedBy["ExecuteBatchStatement"]=["JdbcStatements"];
ntUsedBy["RawSqlList"]=["ExecuteSqlStatement","ExecuteBatchStatement"];
ntUsedBy["FunctionDeclaration"]=["Script","ClassDefinition"];
ntUsedBy["MultiplicativeExpr"]=["AdditiveExpr"];
ntUsedBy["ExecuteSqlStatement"]=["JdbcStatements"];
ntUsedBy["ConstructorDeclaration"]=["ClassDefinition","JavaExtensionDefinition"];
ntUsedBy["IncludeDirective"]=["Directives"];
ntUsedBy["ThrowStatement"]=["Statement"];
ntUsedBy["LocalVariableDeclaration"]=["Statement"];
ntUsedBy["ForStatements"]=["Statement"];
ntUsedBy["ShiftExpr"]=["RelationalExpr"];
ntUsedBy["ExecuteQueryStatement"]=["JdbcStatements"];
ntUsedBy["FormalParameters"]=["ConstructorDeclaration","FunctionDeclaration","LambdaDeclaration","ThreadDeclaration","StartThreadStatement"];
ntUsedBy["ExecStatement"]=["Statement"];
ntUsedBy["SCPStatement"]=["Statement"];
ntUsedBy["SimpleBlock"]=["DoWhileStatement","RepeatStatement","LinesStatement","ScheduleStatement","ExecStatement","PreparedExecuteQueryStatement","ExecuteQueryStatement"];
ntUsedBy["JdbcStatements"]=["Statement"];
ntUsedBy["SgmlStatement"]=["Statement"];
ntUsedBy["JavaClassShortcuts"]=["Directives"];
ntUsedBy["ConditionalExpr"]=["Expr","ConditionalExpr"];
ntUsedBy["ConditionalOrExpr"]=["ConditionalExpr"];
ntUsedBy["PrintArgument"]=["PrintStatement","PrintTableDataStatement"];
ntUsedBy["AtomicExpr"]=["PrimaryExpr"];
ntUsedBy["MailStatement"]=["Statement"];
ntUsedBy["DumpTableStatement"]=["JdbcStatements"];
ntUsedBy["StructAllocator"]=["ConstantDefinition","Assignment","LocalVariableDeclaration","ReturnStatement"];
ntUsedBy["ResumeStatement"]=["Statement"];
ntUsedBy["ConditionalAndExpr"]=["ConditionalOrExpr"];
ntUsedBy["AnonMemberInitList"]=["ObjectAllocator"];
function getUsedBy(id) {
  var arr = ntUsedBy[id];
  if (arr == null) return 'none.';
  var str = '';
  for (var i=0; i<arr.length; ++i) {
    var id = arr[i];
    str += '<a href="javascript:showPanes('_synn.html#synn_'+id+'','synn_'+id+'.html')">'
           +id+'</a> &nbsp; ';
  }
  return str;
}

function listUsedBy(id) {
  id = id.substring(1);
  var arr = ntUsedBy[id];
  if (arr == null) return 'none.';
  var str = '';
  for (var i=0; i<arr.length; ++i) {
    str += '<a href=#' + arr[i] + '>' + arr[i] + '</a> &nbsp; ';
  }
  return str;
}
//--></script>